// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mock_clients is a generated GoMock package.
package mock_clients

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetDownloadSpeed mocks base method.
func (m *MockClient) GetDownloadSpeed() (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDownloadSpeed")
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDownloadSpeed indicates an expected call of GetDownloadSpeed.
func (mr *MockClientMockRecorder) GetDownloadSpeed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDownloadSpeed", reflect.TypeOf((*MockClient)(nil).GetDownloadSpeed))
}

// GetUploadSpeed mocks base method.
func (m *MockClient) GetUploadSpeed() (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUploadSpeed")
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUploadSpeed indicates an expected call of GetUploadSpeed.
func (mr *MockClientMockRecorder) GetUploadSpeed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUploadSpeed", reflect.TypeOf((*MockClient)(nil).GetUploadSpeed))
}
