// Code generated by MockGen. DO NOT EDIT.
// Source: providers.go

// Package mock_providers is a generated GoMock package.
package mock_providers

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	clients "github.com/mrol/speedtest/clients"
)

// MockFinder is a mock of Finder interface.
type MockFinder struct {
	ctrl     *gomock.Controller
	recorder *MockFinderMockRecorder
}

// MockFinderMockRecorder is the mock recorder for MockFinder.
type MockFinderMockRecorder struct {
	mock *MockFinder
}

// NewMockFinder creates a new mock instance.
func NewMockFinder(ctrl *gomock.Controller) *MockFinder {
	mock := &MockFinder{ctrl: ctrl}
	mock.recorder = &MockFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFinder) EXPECT() *MockFinderMockRecorder {
	return m.recorder
}

// GetClientByProviderCode mocks base method.
func (m *MockFinder) GetClientByProviderCode(providerCode string) (clients.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientByProviderCode", providerCode)
	ret0, _ := ret[0].(clients.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientByProviderCode indicates an expected call of GetClientByProviderCode.
func (mr *MockFinderMockRecorder) GetClientByProviderCode(providerCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientByProviderCode", reflect.TypeOf((*MockFinder)(nil).GetClientByProviderCode), providerCode)
}
